window.RISHU_FEATURES=[
{id:'copy-values',category:'Quick Tools',name:'Copy values only',help:'Copy selected values',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load('values');await c.sync();navigator.clipboard?.writeText(r.values.map(x=>x.join('\t')).join('\n'))})},
{id:'clear-formatting',category:'Quick Tools',name:'Clear formatting',help:'Clear selected formatting',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.format.fill.clear();r.format.font.clear();await c.sync()})},
{id:'autofit-columns',category:'Quick Tools',name:'Autofit selected columns',help:'Autofit selection columns',run:async()=>Excel.run(async c=>{c.workbook.getSelectedRange().format.autofitColumns();await c.sync()})},
{id:'trim-spaces',category:'Clean Data',name:'Trim extra spaces',help:'Trim and normalize spaces',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load('values');await c.sync();r.values=r.values.map(a=>a.map(v=>typeof v==='string'?v.trim().replace(/\s+/g,' '):v));await c.sync()})},
{id:'uppercase',category:'Text Tools',name:'UPPERCASE',help:'Convert text to uppercase',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load('values');await c.sync();r.values=r.values.map(a=>a.map(v=>typeof v==='string'?v.toUpperCase():v));await c.sync()})},
{id:'lowercase',category:'Text Tools',name:'lowercase',help:'Convert text to lowercase',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load('values');await c.sync();r.values=r.values.map(a=>a.map(v=>typeof v==='string'?v.toLowerCase():v));await c.sync()})},
{id:'proper-case',category:'Text Tools',name:'Proper Case',help:'Convert text to proper case',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load('values');await c.sync();r.values=r.values.map(a=>a.map(v=>typeof v==='string'?v.toLowerCase().replace(/\b\w/g,m=>m.toUpperCase()):v));await c.sync()})},
{id:'remove-numbers',category:'Text Tools',name:'Remove numbers',help:'Remove digits from text',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load('values');await c.sync();r.values=r.values.map(a=>a.map(v=>typeof v==='string'?v.replace(/\d/g,''):v));await c.sync()})},
{id:'remove-special',category:'Text Tools',name:'Remove special characters',help:'Keep letters numbers and spaces',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load('values');await c.sync();r.values=r.values.map(a=>a.map(v=>typeof v==='string'?v.replace(/[^\p{L}\p{N} ]/gu,''):v));await c.sync()})},
{id:'select-used',category:'Find & Inspect',name:'Select used range',help:'Select used range',run:async()=>Excel.run(async c=>{const r=c.workbook.worksheets.getActiveWorksheet().getUsedRange();r.select();await c.sync()})},
{id:'show-formulas',category:'Formula Tools',name:'Show formulas',help:'Show selected formulas',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load('formulas');await c.sync();alert(r.formulas.flat().join('\n'))})},
{id:'to-values',category:'Formula Tools',name:'Convert formulas to values',help:'Replace formulas with values',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load('values');await c.sync();r.values=r.values;await c.sync()})},
{id:'table-create',category:'Tables',name:'Convert range to Excel Table',help:'Create table from selection',run:async()=>Excel.run(async c=>{c.workbook.tables.add(c.workbook.getSelectedRange(),true);await c.sync()})},
{id:'mean',category:'Analysis',name:'Mean',help:'Write mean beside selection',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load(['values','rowIndex','columnIndex','columnCount']);await c.sync();const n=r.values.flat().filter(v=>typeof v==='number');if(!n.length)throw Error('No numeric values selected');r.worksheet.getCell(r.rowIndex,r.columnIndex+r.columnCount).values=[[n.reduce((a,b)=>a+b,0)/n.length]];await c.sync()})},
{id:'min',category:'Analysis',name:'Minimum',help:'Write minimum beside selection',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load(['values','rowIndex','columnIndex','columnCount']);await c.sync();const n=r.values.flat().filter(v=>typeof v==='number');if(!n.length)throw Error('No numeric values selected');r.worksheet.getCell(r.rowIndex,r.columnIndex+r.columnCount).values=[[Math.min(...n)]];await c.sync()})},
{id:'max',category:'Analysis',name:'Maximum',help:'Write maximum beside selection',run:async()=>Excel.run(async c=>{const r=c.workbook.getSelectedRange();r.load(['values','rowIndex','columnIndex','columnCount']);await c.sync();const n=r.values.flat().filter(v=>typeof v==='number');if(!n.length)throw Error('No numeric values selected');r.worksheet.getCell(r.rowIndex,r.columnIndex+r.columnCount).values=[[Math.max(...n)]];await c.sync()})}
];